# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "xhci_pci" "usbhid" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-ce4bf560-5e00-4541-98f7-32d053d8061c";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-ce4bf560-5e00-4541-98f7-32d053d8061c".device = "/dev/disk/by-uuid/ce4bf560-5e00-4541-98f7-32d053d8061c";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2206-BDF8";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-a1100a54-2434-4df7-814f-1c07900a6644"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
  hardware.parallels.enable = true;
  nixpkgs.config.allowUnfreePackages = [ "prl-tools" ];
}
